### ISSUE TITLE
README.md oluşturulacak

### ISSUE THREAD

**Issue by eser** [acikkaynak/aya-website#13]
Projenin genel amacı, kapsamı, kullanılan teknolojiler ve codebase'e nasıl katkıda bulunulabileceğı ile ilgili bir `README.md`'e ihtiyacımız var.

**Comment by umuthopeyildirim** [comment]
PR request actim bununla ilgili #25

**Comment by eser** [comment]
#25 sayesinde kapatıldı 🥇
