### ISSUE TITLE
Haber kartlarındaki tarih/saat biçimi

### ISSUE THREAD

**Issue by Valthoron** [acikkaynak/aya-website#24]
Haber kartlarındaki tarih ve saat ISO 8601 yerine okunaklı biçimde ve Türkiye saati ile yazılabilir. Örneğin;
> 2023-02-17T12:13:01.489Z

yerine
> 17/02/2023 15:13

veya
> 17 Şubat 2023 Cuma, 15:13

Site başka dilde görüntülendiğinde saat dilimi bilgisi "(GMT+3)" veya "(Istanbul)" gibi eklenebilir.

**Comment by eser** [comment]
yol haritasına ekledim :) teşekkürler @Valthoron

**Comment by Valthoron** [comment]
Nasıl çalıştırıp test edebileceğimi bilseydim pull request'le gelmek isterdim, fakat bilemedim. :)

**Comment by muratGG** [comment]
Türkiye degil her kullanici kendi zaman diliminde goruntulemeli.
