### ISSUE TITLE
Favicon change

### ISSUE THREAD

**Issue by mertssmnoglu** [acikkaynak/aya-website#29]
Default vercel's favicon can be changed with aya's favicon. It's better for branding.

**Comment by yigiterdev** [comment]
Merhaba @eser, bu issue’yu ben alabilir miyim? Basit bir issue fakat bir yerden başlamak lazım.

**Comment by mertssmnoglu** [comment]
@yigiterdev Ben normalde https://favicon.io/ gibi sitelerden direkt bi png'yi ico'ya çevirmeyi düşünmüştüm ama belki ikonda değişiklik olursa daha güzel durabilir. Daire şeklinde olması veya en azından aşırı köşeli olmaması güzel olur bence.
