### ISSUE TITLE
Footer style düzenlenmesi

### ISSUE THREAD

**Issue by alicangunduz** [acikkaynak/aya-website#7]
Merhaba footer son sayfa içeriğine doğrudan temaslı gözükmektedir. 
Bknz : 
![image](https://github.com/acikkaynak/aya-website/assets/54004830/6800fc96-7712-4389-9b5b-a415c0dd74e0)

Bunun daha iyi bir görünüme ulaşması için böyle gözükmesi gerektiğini düşünüyorum.

Bknz :
![image](https://github.com/acikkaynak/aya-website/assets/54004830/f4d5cb87-3583-4496-ae8c-ce534d2a34bc)

Bu görünüme ulaşması için eklenmesi gereken css kodu : 

```
position: fixed; 
bottom: 0; 
left: 0; 
right: 0;"
```

**Comment by eser** [comment]
Mobilde filan nasıl görünecek emin olmasam da, bir deneyeceğim. Çok teşekkürler :)

**Comment by eser** [comment]
Düzeltildi, teşekkürler 🍾
